"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarDays,CheckCircle2,ChevronRight,Heart,Home,ListChecks,LockKeyhole,Plus,ReceiptRussianRuble,ShoppingBasket,Target,Trash2,Users } from "lucide-react";
type Item={id:number;kind:string;title:string;details:string;status:string;owner:string;dueDate:string;amount:number;isPrivate:boolean};
const nav=[["home","Обзор",Home],["task","Задачи",ListChecks],["calendar","Календарь",CalendarDays],["shopping","Покупки",ShoppingBasket],["finance","Бюджет",ReceiptRussianRuble],["goal","Цели",Target],["private","Личное",LockKeyhole]] as const;
const titles:Record<string,string>={home:"Добро пожаловать домой",task:"Семейные задачи",calendar:"Наш календарь",shopping:"Список покупок",finance:"Семейный бюджет",goal:"Наши цели",private:"Личное пространство"};
export default function HomePage(){
 const[configured,setConfigured]=useState<boolean|null>(null),[name,setName]=useState("Светлана"),[pin,setPin]=useState(""),[member,setMember]=useState("");
 const[items,setItems]=useState<Item[]>([]),[section,setSection]=useState("home"),[showAdd,setShowAdd]=useState(false),[error,setError]=useState(""),[signingIn,setSigningIn]=useState(false);
 const auth={"x-family-name":encodeURIComponent(name),"x-family-pin":pin};
 async function load(){if(pin.length<4){setError("Введите PIN-код — минимум 4 цифры");return}setSigningIn(true);setError("");try{const r=await fetch("/api/family",{headers:auth}),d=await r.json();setConfigured(d.configured);if(r.ok&&d.member){setMember(d.member);setItems(d.items)}else setError(d.error||"Не удалось войти")}catch{setError("Нет связи с приложением. Попробуйте ещё раз.")}finally{setSigningIn(false)}}
 useEffect(()=>{fetch("/api/family").then(r=>r.json()).then(d=>setConfigured(d.configured))},[]);
 const visible=useMemo(()=>items.filter(i=>section==="private"?i.isPrivate:i.kind===section&&!i.isPrivate),[items,section]);
 async function setup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/family",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"setup",svetlanaPin:f.get("svetlana"),alexeyPin:f.get("alexey")})}),d=await r.json();if(r.ok){setConfigured(true);setError("")}else setError(d.error)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={kind:section==="private"?"task":section,title:f.get("title"),details:f.get("details"),dueDate:f.get("date"),amount:Number(f.get("amount")||0),owner:f.get("owner"),isPrivate:section==="private"};const r=await fetch("/api/family",{method:"POST",headers:{...auth,"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){setShowAdd(false);await load()}else setError((await r.json()).error)}
 async function advance(i:Item){const status=i.status==="planned"?"doing":i.status==="doing"?"done":"planned";await fetch("/api/family",{method:"PATCH",headers:{...auth,"content-type":"application/json"},body:JSON.stringify({id:i.id,status})});load()}
 async function remove(id:number){await fetch(`/api/family?id=${id}`,{method:"DELETE",headers:auth});load()}
 if(configured===null)return <main className="center"><div className="loader"/></main>;
 if(!configured)return <main className="center"><form className="auth-card" onSubmit={setup}><div className="brand-mark"><Heart/></div><h1>Наша семья</h1><p>Место для общих планов, забот и мечтаний</p><label>PIN Светланы<input name="svetlana" type="password" inputMode="numeric" minLength={4} maxLength={8} required/></label><label>PIN Алексея<input name="alexey" type="password" inputMode="numeric" minLength={4} maxLength={8} required/></label>{error&&<div className="error">{error}</div>}<button>Создать семейное пространство</button></form></main>;
 if(!member)return <main className="center"><form className="auth-card" onSubmit={e=>{e.preventDefault();void load()}}><div className="brand-mark"><Heart/></div><h1>Наша семья</h1><p>Рады видеть вас снова</p><div className="people"><button type="button" className={name==="Светлана"?"active":""} onClick={()=>{setName("Светлана");setError("")}}>Светлана</button><button type="button" className={name==="Алексей"?"active":""} onClick={()=>{setName("Алексей");setError("")}}>Алексей</button></div><label>PIN-код<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,8))} type="password" inputMode="numeric" minLength={4} maxLength={8} required/></label>{error&&<div className="error">{error}</div>}<button type="submit" disabled={pin.length<4||signingIn}>{signingIn?"Входим…":"Войти"}</button></form></main>;
 const shared=items.filter(i=>!i.isPrivate),pending=shared.filter(i=>i.status!=="done"),done=shared.filter(i=>i.status==="done"),shopping=shared.filter(i=>i.kind==="shopping"),goals=shared.filter(i=>i.kind==="goal"),money=shared.filter(i=>i.kind==="finance").reduce((s,i)=>s+i.amount,0);
 return <main className="app-shell cozy">
  <aside><div className="logo"><span><Heart/></span><div><b>Наша семья</b><small>наш общий дом</small></div></div><nav>{nav.map(([id,title,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon/>{title}{id!=="home"&&<em>{items.filter(i=>id==="private"?i.isPrivate:i.kind===id&&!i.isPrivate).length}</em>}</button>)}</nav><div className="profile"><div>{member[0]}</div><span><b>{member}</b><small>Дома</small></span><button onClick={()=>{setMember("");setPin("")}}>Выйти</button></div></aside>
  <section className={`workspace section-${section}`}><header><div><p>{new Date().toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}</p><h1>{titles[section]}</h1></div>{section!=="home"&&<button className="add" onClick={()=>setShowAdd(true)}><Plus/>Добавить</button>}</header>
  {section==="home"?<div className="home-view">
   <div className="welcome"><div><span>♡ Семейный обзор</span><h2>Сегодня всё важное<br/>в одном месте</h2><p>{pending.length? `Осталось ${pending.length} общих дел. Вы справитесь вместе.`:"Все общие дела выполнены — время побыть вместе."}</p></div><Heart/></div>
   <div className="stat-grid"><button onClick={()=>setSection("task")}><span className="peach"><ListChecks/></span><b>{pending.length}</b><small>дел ожидают</small><ChevronRight/></button><button onClick={()=>setSection("shopping")}><span className="mint"><ShoppingBasket/></span><b>{shopping.length}</b><small>покупок в списке</small><ChevronRight/></button><button onClick={()=>setSection("goal")}><span className="sun"><Target/></span><b>{goals.length}</b><small>общих целей</small><ChevronRight/></button><button onClick={()=>setSection("finance")}><span className="blue"><ReceiptRussianRuble/></span><b>{money.toLocaleString("ru-RU")} ₽</b><small>в бюджете</small><ChevronRight/></button></div>
   <div className="home-columns"><section><div className="section-title"><h3>Ближайшие дела</h3><button onClick={()=>setSection("task")}>Все задачи</button></div>{pending.slice(0,4).map(i=><div className="mini-row" key={i.id}><button onClick={()=>advance(i)}><CheckCircle2/></button><div><b>{i.title}</b><small>{i.owner}{i.dueDate?` · ${new Date(i.dueDate).toLocaleDateString("ru-RU")}`:""}</small></div></div>)}{!pending.length&&<p className="soft-empty">Здесь появятся ближайшие семейные дела</p>}</section><section className="together"><Heart/><h3>Вместе получается больше</h3><p>Вы уже завершили {done.length} общих дел.</p><div><span style={{width:`${Math.min(100,done.length/(shared.length||1)*100)}%`}}/></div></section></div>
  </div>:section==="task"?<div className="kanban">{[["planned","Запланировано"],["doing","В процессе"],["done","Готово"]].map(([status,title])=><section key={status}><h3>{title}<span>{visible.filter(i=>i.status===status).length}</span></h3>{visible.filter(i=>i.status===status).map(i=><ItemCard key={i.id} item={i} advance={advance} remove={remove}/>)}</section>)}</div>
  :section==="finance"?<><div className="finance-hero"><div><small>Сумма всех записей</small><strong>{money.toLocaleString("ru-RU")} ₽</strong><p>Общий семейный финансовый обзор</p></div><div className="donut"><span>{visible.length}</span><small>записей</small></div></div><CardGrid items={visible} advance={advance} remove={remove}/></>
  :section==="goal"?<div className="goals-grid">{visible.length?visible.map((i,n)=><article className="goal-card" key={i.id}><div className="goal-icon"><Target/></div><small>Семейная цель {n+1}</small><h3>{i.title}</h3><p>{i.details||"Шаг за шагом — вместе"}</p><div className="goal-progress"><span style={{width:i.status==="done"?"100%":i.status==="doing"?"55%":"15%"}}/></div><footer><button onClick={()=>advance(i)}>Продвинуть цель</button><button onClick={()=>remove(i.id)}><Trash2/></button></footer></article>):<Empty onAdd={()=>setShowAdd(true)}/>}</div>
  :section==="shopping"?<div className="shopping-list">{visible.length?visible.map(i=><label key={i.id} className={i.status==="done"?"checked":""}><button onClick={()=>advance(i)}><CheckCircle2/></button><span><b>{i.title}</b><small>{i.details||i.owner}</small></span>{i.amount>0&&<strong>{i.amount.toLocaleString("ru-RU")} ₽</strong>}<button onClick={()=>remove(i.id)}><Trash2/></button></label>):<Empty onAdd={()=>setShowAdd(true)}/>}</div>
  :<CardGrid items={visible} advance={advance} remove={remove}/>}
  </section>
  {showAdd&&<div className="modal-bg" onMouseDown={()=>setShowAdd(false)}><form className="modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><h2>Добавить в «{titles[section]}»</h2><label>Название<input name="title" autoFocus required/></label><label>Описание<textarea name="details" rows={3}/></label><div className="form-row"><label>Дата<input name="date" type="date"/></label>{section==="finance"&&<label>Сумма, ₽<input name="amount" type="number"/></label>}</div>{section!=="private"&&<label>Для кого<select name="owner"><option>Общее</option><option>Светлана</option><option>Алексей</option></select></label>}<div className="modal-actions"><button type="button" onClick={()=>setShowAdd(false)}>Отмена</button><button className="primary">Сохранить</button></div></form></div>}
 </main>
}
function ItemCard({item,advance,remove}:{item:Item;advance:(i:Item)=>void;remove:(id:number)=>void}){return <article className="item-card"><div className={`status ${item.status}`}>{item.status==="planned"?"План":item.status==="doing"?"Делаем":"Готово"}</div><h3>{item.title}</h3>{item.details&&<p>{item.details}</p>}<footer><span>{item.owner}</span>{item.dueDate&&<time>{new Date(item.dueDate).toLocaleDateString("ru-RU")}</time>}<button onClick={()=>advance(item)}><CheckCircle2/></button><button onClick={()=>remove(item.id)}><Trash2/></button></footer></article>}
function CardGrid({items,advance,remove}:{items:Item[];advance:(i:Item)=>void;remove:(id:number)=>void}){return <div className="board">{items.length?items.map(i=><ItemCard key={i.id} item={i} advance={advance} remove={remove}/>):<Empty onAdd={()=>{}}/>}</div>}
function Empty({onAdd}:{onAdd:()=>void}){return <div className="empty"><Heart/><h2>Здесь пока тихо</h2><p>Добавьте первую семейную запись.</p><button onClick={onAdd}><Plus/>Добавить</button></div>}
